// Generated by CoffeeScript 1.4.0
(function() {

  (function($) {
    return $.fn.iframe = function(src, options) {
      var defaults, iDoc, iWin, iframe, opt;
      defaults = {
        win: window,
        doc: document,
        method: "replaceWith"
      };
      opt = $.extend(defaults, options);
      iframe = opt.doc.createElement('iframe');
      iframe.scrolling = 'no';
      iframe.frameBorder = '0';
      $(this)[opt.method](iframe);
      iWin = iframe.contentWindow;
      iDoc = iWin.document;
      iWin.foo = "foo";
      iDoc.open();
      iDoc.write(src);
      iDoc.close();
      return $(iframe);
    };
  })(jQuery);

  window.src = "<!DOCTYPE html>\n<html>\n<head>\n<script src=\"/js/jquery-1.8.3.js\"></script>\n</head>\n<body style='background-color:red'>\n<h1>hello</h1>\n<script>\n$(function(){\n  alert(foo);\n  //for(var i=0;i<n;i++){\n  //  document.write(\"<h1>hello</h1>\");\n  //}\n});\n</script>\n</body>\n</html>";

}).call(this);
